[package]
name = "async-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.snowboard]
path = "../.."
features = ["async", "websocket"]

[dependencies]
async-std = "1.12.0"
